import { TarotCard } from './types'

export const ALL_CARDS: TarotCard[] = [
  // ─── MAJOR ARCANA ────────────────────────────────────────────────────────────
  {
    id: 'major-0', numericId: 0, arcana: 'major',
    name: 'The Fool', nameUa: 'Блазень',
    keywords: ['beginnings', 'innocence', 'spontaneity', 'adventure'],
    keywordsUa: ['початок', 'невинність', 'спонтанність', 'пригода'],
    image: '/cards/major-0.jpg',
    meaning: { upright: 'New beginnings, innocence, adventure, free spirit', reversed: 'Recklessness, risk-taking, holding back' },
    meaningUa: { upright: 'Нові початки, невинність, пригода, вільний дух', reversed: 'Необережність, ризик, страх дії' },
  },
  {
    id: 'major-1', numericId: 1, arcana: 'major',
    name: 'The Magician', nameUa: 'Маг',
    keywords: ['manifestation', 'resourcefulness', 'power', 'inspired action'],
    keywordsUa: ['маніфестація', 'винахідливість', 'сила', 'дія'],
    image: '/cards/major-1.jpg',
    meaning: { upright: 'Manifestation, resourcefulness, power, inspired action', reversed: 'Manipulation, poor planning, untapped talents' },
    meaningUa: { upright: 'Маніфестація, спритність, воля, натхненна дія', reversed: 'Маніпуляція, погане планування, нереалізований талант' },
  },
  {
    id: 'major-2', numericId: 2, arcana: 'major',
    name: 'The High Priestess', nameUa: 'Верховна Жриця',
    keywords: ['intuition', 'mystery', 'inner voice', 'subconscious'],
    keywordsUa: ['інтуїція', 'таємниця', 'внутрішній голос', 'підсвідомість'],
    image: '/cards/major-2.jpg',
    meaning: { upright: 'Intuition, sacred knowledge, divine feminine, the subconscious mind', reversed: 'Secrets, disconnection from intuition, withdrawal' },
    meaningUa: { upright: 'Інтуїція, священне знання, підсвідомість', reversed: 'Таємниці, відрив від інтуїції, самоізоляція' },
  },
  {
    id: 'major-3', numericId: 3, arcana: 'major',
    name: 'The Empress', nameUa: 'Імператриця',
    keywords: ['femininity', 'beauty', 'nature', 'abundance'],
    keywordsUa: ['жіночність', 'краса', 'природа', 'достаток'],
    image: '/cards/major-3.jpg',
    meaning: { upright: 'Femininity, beauty, nature, nurturing, abundance', reversed: 'Creative block, dependence on others' },
    meaningUa: { upright: 'Жіночність, краса, природа, турбота, достаток', reversed: 'Творчий блок, залежність від інших' },
  },
  {
    id: 'major-4', numericId: 4, arcana: 'major',
    name: 'The Emperor', nameUa: 'Імператор',
    keywords: ['authority', 'structure', 'control', 'fatherhood'],
    keywordsUa: ['авторитет', 'структура', 'контроль', 'батьківство'],
    image: '/cards/major-4.jpg',
    meaning: { upright: 'Authority, establishment, structure, a father figure', reversed: 'Domination, excessive control, rigidity' },
    meaningUa: { upright: 'Авторитет, структура, стабільність, захист', reversed: 'Тиранія, надмірний контроль, жорсткість' },
  },
  {
    id: 'major-5', numericId: 5, arcana: 'major',
    name: 'The Hierophant', nameUa: 'Ієрофант',
    keywords: ['tradition', 'conformity', 'morality', 'ethics'],
    keywordsUa: ['традиція', 'відповідність', 'мораль', 'етика'],
    image: '/cards/major-5.jpg',
    meaning: { upright: 'Spiritual wisdom, tradition, conformity, morality', reversed: 'Personal beliefs, freedom, challenging the status quo' },
    meaningUa: { upright: 'Духовна мудрість, традиція, інститути, порядок', reversed: 'Особисті переконання, бунт, свобода' },
  },
  {
    id: 'major-6', numericId: 6, arcana: 'major',
    name: 'The Lovers', nameUa: 'Закохані',
    keywords: ['love', 'harmony', 'relationships', 'choices'],
    keywordsUa: ['кохання', 'гармонія', 'стосунки', 'вибір'],
    image: '/cards/major-6.jpg',
    meaning: { upright: 'Love, harmony, relationships, values alignment, choices', reversed: 'Self-love, disharmony, imbalance, misalignment of values' },
    meaningUa: { upright: 'Кохання, гармонія, вибір, єднання', reversed: 'Дисгармонія, розрив цінностей, нерозуміння' },
  },
  {
    id: 'major-7', numericId: 7, arcana: 'major',
    name: 'The Chariot', nameUa: 'Колісниця',
    keywords: ['control', 'willpower', 'success', 'determination'],
    keywordsUa: ['контроль', 'воля', 'успіх', 'рішучість'],
    image: '/cards/major-7.jpg',
    meaning: { upright: 'Control, willpower, success, action, determination', reversed: 'Self-discipline, opposition, lack of direction' },
    meaningUa: { upright: 'Контроль, воля, перемога, рух уперед', reversed: 'Самодисципліна, опір, відсутність напряму' },
  },
  {
    id: 'major-8', numericId: 8, arcana: 'major',
    name: 'Strength', nameUa: 'Сила',
    keywords: ['strength', 'courage', 'patience', 'influence'],
    keywordsUa: ['сила', 'мужність', 'терпіння', 'вплив'],
    image: '/cards/major-8.jpg',
    meaning: { upright: 'Inner strength, bravery, compassion, focus', reversed: 'Self-doubt, weakness, insecurity' },
    meaningUa: { upright: 'Внутрішня сила, хоробрість, співчуття, стриманість', reversed: 'Сумніви, слабкість, невпевненість' },
  },
  {
    id: 'major-9', numericId: 9, arcana: 'major',
    name: 'The Hermit', nameUa: 'Відлюдник',
    keywords: ['soul-searching', 'introspection', 'inner guidance', 'solitude'],
    keywordsUa: ['самопізнання', 'інтроспекція', 'внутрішнє керівництво', 'самотність'],
    image: '/cards/major-9.jpg',
    meaning: { upright: 'Soul-searching, introspection, being alone, inner guidance', reversed: 'Isolation, loneliness, withdrawal' },
    meaningUa: { upright: 'Самопізнання, мудрість, усамітнення, внутрішній світло', reversed: 'Ізоляція, самотність, замкнутість' },
  },
  {
    id: 'major-10', numericId: 10, arcana: 'major',
    name: 'Wheel of Fortune', nameUa: 'Колесо Долі',
    keywords: ['change', 'cycles', 'fate', 'destiny'],
    keywordsUa: ['зміни', 'цикли', 'доля', 'призначення'],
    image: '/cards/major-10.jpg',
    meaning: { upright: 'Good luck, karma, life cycles, destiny, turning point', reversed: 'Bad luck, resistance to change, breaking cycles' },
    meaningUa: { upright: 'Удача, карма, цикли життя, поворотний момент', reversed: 'Невдача, опір змінам, розрив циклів' },
  },
  {
    id: 'major-11', numericId: 11, arcana: 'major',
    name: 'Justice', nameUa: 'Справедливість',
    keywords: ['justice', 'fairness', 'truth', 'cause and effect'],
    keywordsUa: ['справедливість', 'чесність', 'правда', 'причина і наслідок'],
    image: '/cards/major-11.jpg',
    meaning: { upright: 'Justice, fairness, truth, cause and effect, law', reversed: 'Unfairness, lack of accountability, dishonesty' },
    meaningUa: { upright: 'Справедливість, чесність, правда, закон', reversed: 'Несправедливість, відсутність відповідальності, нечесність' },
  },
  {
    id: 'major-12', numericId: 12, arcana: 'major',
    name: 'The Hanged Man', nameUa: 'Повішений',
    keywords: ['pause', 'surrender', 'letting go', 'new perspectives'],
    keywordsUa: ['пауза', 'здача', 'відпускання', 'нові перспективи'],
    image: '/cards/major-12.jpg',
    meaning: { upright: 'Pause, surrender, letting go, new perspectives', reversed: 'Delays, resistance, stalling, indecision' },
    meaningUa: { upright: 'Пауза, відпускання, нові погляди, жертва', reversed: 'Затримки, опір, нерішучість' },
  },
  {
    id: 'major-13', numericId: 13, arcana: 'major',
    name: 'Death', nameUa: 'Смерть',
    keywords: ['endings', 'change', 'transformation', 'transition'],
    keywordsUa: ['завершення', 'зміни', 'трансформація', 'перехід'],
    image: '/cards/major-13.jpg',
    meaning: { upright: 'Endings, change, transformation, transition', reversed: 'Resistance to change, personal transformation, inner purging' },
    meaningUa: { upright: 'Кінець, зміни, трансформація, перехід', reversed: 'Опір змінам, внутрішнє очищення' },
  },
  {
    id: 'major-14', numericId: 14, arcana: 'major',
    name: 'Temperance', nameUa: 'Поміркованість',
    keywords: ['balance', 'moderation', 'patience', 'purpose'],
    keywordsUa: ['баланс', 'помірність', 'терпіння', 'мета'],
    image: '/cards/major-14.jpg',
    meaning: { upright: 'Balance, moderation, patience, purpose', reversed: 'Imbalance, excess, self-healing, re-alignment' },
    meaningUa: { upright: 'Баланс, помірність, терпіння, гармонія', reversed: 'Дисбаланс, надмірність, переналаштування' },
  },
  {
    id: 'major-15', numericId: 15, arcana: 'major',
    name: 'The Devil', nameUa: 'Диявол',
    keywords: ['shadow self', 'attachment', 'addiction', 'restriction'],
    keywordsUa: ['тінь', 'прив\'язаність', 'залежність', 'обмеження'],
    image: '/cards/major-15.jpg',
    meaning: { upright: 'Shadow self, attachment, addiction, restriction, sexuality', reversed: 'Releasing limiting beliefs, exploring dark thoughts, detachment' },
    meaningUa: { upright: 'Тінь, прив\'язаність, залежність, спокуса', reversed: 'Звільнення, усвідомлення пастки, відрив' },
  },
  {
    id: 'major-16', numericId: 16, arcana: 'major',
    name: 'The Tower', nameUa: 'Вежа',
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation'],
    keywordsUa: ['раптові зміни', 'потрясіння', 'хаос', 'одкровення'],
    image: '/cards/major-16.jpg',
    meaning: { upright: 'Sudden change, upheaval, chaos, revelation, awakening', reversed: 'Personal transformation, fear of change, averting disaster' },
    meaningUa: { upright: 'Раптові зміни, руйнація, пробудження', reversed: 'Уникнення катастрофи, внутрішня трансформація' },
  },
  {
    id: 'major-17', numericId: 17, arcana: 'major',
    name: 'The Star', nameUa: 'Зірка',
    keywords: ['hope', 'faith', 'purpose', 'renewal'],
    keywordsUa: ['надія', 'віра', 'мета', 'оновлення'],
    image: '/cards/major-17.jpg',
    meaning: { upright: 'Hope, faith, purpose, renewal, spirituality', reversed: 'Lack of faith, despair, self-trust, disconnection' },
    meaningUa: { upright: 'Надія, віра, мета, духовність, оновлення', reversed: 'Відчай, втрата віри, відключення' },
  },
  {
    id: 'major-18', numericId: 18, arcana: 'major',
    name: 'The Moon', nameUa: 'Місяць',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious'],
    keywordsUa: ['ілюзія', 'страх', 'тривога', 'підсвідомість'],
    image: '/cards/major-18.jpg',
    meaning: { upright: 'Illusion, fear, anxiety, subconscious, intuition', reversed: 'Release of fear, repressed emotion, inner confusion' },
    meaningUa: { upright: 'Ілюзія, страх, тривога, підсвідомість', reversed: 'Звільнення від страху, пригнічені емоції' },
  },
  {
    id: 'major-19', numericId: 19, arcana: 'major',
    name: 'The Sun', nameUa: 'Сонце',
    keywords: ['positivity', 'fun', 'warmth', 'success'],
    keywordsUa: ['позитив', 'радість', 'тепло', 'успіх'],
    image: '/cards/major-19.jpg',
    meaning: { upright: 'Positivity, fun, warmth, success, vitality', reversed: 'Inner child, feeling down, overly optimistic' },
    meaningUa: { upright: 'Позитив, радість, успіх, вітальність', reversed: 'Пригніченість, надмірний оптимізм' },
  },
  {
    id: 'major-20', numericId: 20, arcana: 'major',
    name: 'Judgement', nameUa: 'Суд',
    keywords: ['judgement', 'rebirth', 'inner calling', 'absolution'],
    keywordsUa: ['суд', 'відродження', 'покликання', 'відпущення'],
    image: '/cards/major-20.jpg',
    meaning: { upright: 'Judgement, rebirth, inner calling, absolution', reversed: 'Self-doubt, inner critic, ignoring the call' },
    meaningUa: { upright: 'Суд, відродження, покликання, переосмислення', reversed: 'Самосумнів, внутрішній критик' },
  },
  {
    id: 'major-21', numericId: 21, arcana: 'major',
    name: 'The World', nameUa: 'Світ',
    keywords: ['completion', 'integration', 'accomplishment', 'travel'],
    keywordsUa: ['завершення', 'інтеграція', 'досягнення', 'подорож'],
    image: '/cards/major-21.jpg',
    meaning: { upright: 'Completion, integration, accomplishment, travel', reversed: 'Seeking personal closure, short-cuts, delays' },
    meaningUa: { upright: 'Завершення, інтеграція, успіх, цілісність', reversed: 'Затримки, незавершеність, пошук виходу' },
  },

  // ─── MINOR ARCANA — WANDS (Жезли) ───────────────────────────────────────────
  {
    id: 'wands-1', numericId: 23, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Ace of Wands', nameUa: 'Туз Жезлів',
    keywords: ['inspiration', 'new opportunities', 'growth', 'potential'],
    keywordsUa: ['натхнення', 'нові можливості', 'зростання', 'потенціал'],
    image: '/cards/wands-1.jpg',
    meaning: { upright: 'Inspiration, new opportunities, growth, potential', reversed: 'Delays, lack of motivation, frustration' },
    meaningUa: { upright: 'Натхнення, нові можливості, творчий потенціал', reversed: 'Затримки, відсутність мотивації' },
  },
  {
    id: 'wands-2', numericId: 24, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Two of Wands', nameUa: 'Двійка Жезлів',
    keywords: ['future planning', 'progress', 'decisions', 'discovery'],
    keywordsUa: ['планування', 'прогрес', 'рішення', 'відкриття'],
    image: '/cards/wands-2.jpg',
    meaning: { upright: 'Future planning, progress, decisions, discovery', reversed: 'Fear of unknown, lack of planning' },
    meaningUa: { upright: 'Планування майбутнього, прогрес, рішення', reversed: 'Страх невідомого, відсутність плану' },
  },
  {
    id: 'wands-3', numericId: 25, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Three of Wands', nameUa: 'Трійка Жезлів',
    keywords: ['expansion', 'foresight', 'overseas opportunities', 'looking ahead'],
    keywordsUa: ['розширення', 'передбачення', 'можливості', 'погляд уперед'],
    image: '/cards/wands-3.jpg',
    meaning: { upright: 'Expansion, foresight, overseas opportunities', reversed: 'Obstacles, delays, frustration with slow progress' },
    meaningUa: { upright: 'Розширення, далекоглядність, нові горизонти', reversed: 'Перешкоди, затримки' },
  },
  {
    id: 'wands-4', numericId: 26, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Four of Wands', nameUa: 'Четвірка Жезлів',
    keywords: ['celebration', 'joy', 'harmony', 'relaxation'],
    keywordsUa: ['святкування', 'радість', 'гармонія', 'відпочинок'],
    image: '/cards/wands-4.jpg',
    meaning: { upright: 'Celebration, joy, harmony, relaxation, homecoming', reversed: 'Lack of support, instability at home' },
    meaningUa: { upright: 'Свято, радість, гармонія, стабільність дому', reversed: 'Нестабільність, відсутність підтримки' },
  },
  {
    id: 'wands-5', numericId: 27, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Five of Wands', nameUa: "П'ятірка Жезлів",
    keywords: ['conflict', 'disagreements', 'competition', 'tension'],
    keywordsUa: ['конфлікт', 'суперечки', 'конкуренція', 'напруга'],
    image: '/cards/wands-5.jpg',
    meaning: { upright: 'Conflict, disagreements, competition, tension, diversity', reversed: 'Inner conflict, conflict avoidance' },
    meaningUa: { upright: 'Конфлікт, суперечки, конкуренція', reversed: 'Внутрішній конфлікт, уникнення сварок' },
  },
  {
    id: 'wands-6', numericId: 28, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Six of Wands', nameUa: 'Шістка Жезлів',
    keywords: ['success', 'public recognition', 'progress', 'self-confidence'],
    keywordsUa: ['успіх', 'визнання', 'прогрес', 'впевненість'],
    image: '/cards/wands-6.jpg',
    meaning: { upright: 'Success, public recognition, progress, self-confidence', reversed: 'Private achievement, fall from grace' },
    meaningUa: { upright: 'Успіх, визнання, тріумф, впевненість', reversed: 'Падіння, неприйняття' },
  },
  {
    id: 'wands-7', numericId: 29, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Seven of Wands', nameUa: 'Сімка Жезлів',
    keywords: ['challenge', 'competition', 'protection', 'perseverance'],
    keywordsUa: ['виклик', 'конкуренція', 'захист', 'наполегливість'],
    image: '/cards/wands-7.jpg',
    meaning: { upright: 'Challenge, competition, protection, perseverance', reversed: 'Exhaustion, giving up, overwhelmed' },
    meaningUa: { upright: 'Виклик, захист позицій, наполегливість', reversed: 'Виснаження, здача позицій' },
  },
  {
    id: 'wands-8', numericId: 30, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Eight of Wands', nameUa: 'Вісімка Жезлів',
    keywords: ['speed', 'action', 'air travel', 'movement'],
    keywordsUa: ['швидкість', 'дія', 'рух', 'подорож'],
    image: '/cards/wands-8.jpg',
    meaning: { upright: 'Speed, action, air travel, movement, swift change', reversed: 'Delays, frustration, resisting change' },
    meaningUa: { upright: 'Швидкість, дія, рух, стрімкі зміни', reversed: 'Затримки, опір змінам' },
  },
  {
    id: 'wands-9', numericId: 31, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Nine of Wands', nameUa: "Дев'ятка Жезлів",
    keywords: ['resilience', 'courage', 'persistence', 'test of faith'],
    keywordsUa: ['стійкість', 'мужність', 'наполегливість', 'випробування'],
    image: '/cards/wands-9.jpg',
    meaning: { upright: 'Resilience, courage, persistence, test of faith, boundaries', reversed: 'Exhaustion, fatigue, questioning motivations' },
    meaningUa: { upright: 'Стійкість, мужність, останні сили', reversed: 'Виснаження, сумніви' },
  },
  {
    id: 'wands-10', numericId: 32, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Ten of Wands', nameUa: 'Десятка Жезлів',
    keywords: ['burden', 'extra responsibility', 'hard work', 'completion'],
    keywordsUa: ['тягар', 'відповідальність', 'важка праця', 'завершення'],
    image: '/cards/wands-10.jpg',
    meaning: { upright: 'Burden, extra responsibility, hard work, completion', reversed: 'Taking on too much, avoiding responsibility' },
    meaningUa: { upright: 'Тягар, надмірна відповідальність, завершення', reversed: 'Надмірне навантаження, уникнення обов\'язків' },
  },
  {
    id: 'wands-11', numericId: 33, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Page of Wands', nameUa: 'Паж Жезлів',
    keywords: ['enthusiasm', 'exploration', 'discovery', 'free spirit'],
    keywordsUa: ['ентузіазм', 'дослідження', 'відкриття', 'вільний дух'],
    image: '/cards/wands-11.jpg',
    meaning: { upright: 'Enthusiasm, exploration, discovery, free spirit', reversed: 'Lack of direction, procrastination, creating conflict' },
    meaningUa: { upright: 'Ентузіазм, дослідження, творче натхнення', reversed: 'Відсутність напряму, прокрастинація' },
  },
  {
    id: 'wands-12', numericId: 34, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Knight of Wands', nameUa: 'Лицар Жезлів',
    keywords: ['action', 'adventure', 'fearlessness', 'energy'],
    keywordsUa: ['дія', 'пригода', 'безстрашність', 'енергія'],
    image: '/cards/wands-12.jpg',
    meaning: { upright: 'Action, adventure, fearlessness, energy', reversed: 'Anger, impulsiveness, recklessness' },
    meaningUa: { upright: 'Дія, пригода, безстрашність, енергія', reversed: 'Гнів, імпульсивність, безрозсудність' },
  },
  {
    id: 'wands-13', numericId: 35, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'Queen of Wands', nameUa: 'Королева Жезлів',
    keywords: ['courage', 'confidence', 'independence', 'social butterfly'],
    keywordsUa: ['сміливість', 'впевненість', 'незалежність', 'харизма'],
    image: '/cards/wands-13.jpg',
    meaning: { upright: 'Courage, confidence, independence, social butterfly, determination', reversed: 'Self-respect, self-confidence, introverted' },
    meaningUa: { upright: 'Сміливість, впевненість, харизма, сила', reversed: 'Самоповага, замкнутість, роздратованість' },
  },
  {
    id: 'wands-14', numericId: 36, arcana: 'minor', suit: 'wands', suitUa: 'Жезлів',
    name: 'King of Wands', nameUa: 'Король Жезлів',
    keywords: ['natural-born leader', 'vision', 'entrepreneur', 'honour'],
    keywordsUa: ['природжений лідер', 'бачення', 'підприємець', 'честь'],
    image: '/cards/wands-14.jpg',
    meaning: { upright: 'Natural-born leader, vision, entrepreneur, honour', reversed: 'Impulsiveness, ruthlessness, overbearing' },
    meaningUa: { upright: 'Природжений лідер, бачення, честь', reversed: 'Імпульсивність, жорстокість' },
  },

  // ─── MINOR ARCANA — CUPS (Кубки) ─────────────────────────────────────────────
  {
    id: 'cups-1', numericId: 37, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Ace of Cups', nameUa: 'Туз Кубків',
    keywords: ['love', 'new relationships', 'compassion', 'creativity'],
    keywordsUa: ['кохання', 'нові стосунки', 'співчуття', 'творчість'],
    image: '/cards/cups-1.jpg',
    meaning: { upright: 'Love, new relationships, compassion, creativity', reversed: 'Self-love, intuition, repressed emotions' },
    meaningUa: { upright: 'Кохання, нові стосунки, творчість, духовність', reversed: 'Самокохання, пригнічені емоції' },
  },
  {
    id: 'cups-2', numericId: 38, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Two of Cups', nameUa: 'Двійка Кубків',
    keywords: ['unified love', 'partnership', 'mutual attraction'],
    keywordsUa: ['єдине кохання', 'партнерство', 'взаємна привабливість'],
    image: '/cards/cups-2.jpg',
    meaning: { upright: 'Unified love, partnership, mutual attraction', reversed: 'Self-love, break-ups, disharmony' },
    meaningUa: { upright: 'Єдність, партнерство, взаємна любов', reversed: 'Розрив, дисгармонія' },
  },
  {
    id: 'cups-3', numericId: 39, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Three of Cups', nameUa: 'Трійка Кубків',
    keywords: ['celebration', 'friendship', 'creativity', 'collaborations'],
    keywordsUa: ['свято', 'дружба', 'творчість', 'співпраця'],
    image: '/cards/cups-3.jpg',
    meaning: { upright: 'Celebration, friendship, creativity, collaborations', reversed: 'Independence, alone time, gossip' },
    meaningUa: { upright: 'Свято, дружба, творчість, єднання', reversed: 'Незалежність, плітки' },
  },
  {
    id: 'cups-4', numericId: 40, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Four of Cups', nameUa: 'Четвірка Кубків',
    keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation'],
    keywordsUa: ['медитація', 'споглядання', 'апатія', 'переосмислення'],
    image: '/cards/cups-4.jpg',
    meaning: { upright: 'Meditation, contemplation, apathy, reevaluation', reversed: 'Sudden awareness, choosing happiness, acceptance' },
    meaningUa: { upright: 'Медитація, апатія, переосмислення', reversed: 'Усвідомлення, прийняття' },
  },
  {
    id: 'cups-5', numericId: 41, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Five of Cups', nameUa: "П'ятірка Кубків",
    keywords: ['regret', 'failure', 'disappointment', 'pessimism'],
    keywordsUa: ['жаль', 'провал', 'розчарування', 'песимізм'],
    image: '/cards/cups-5.jpg',
    meaning: { upright: 'Regret, failure, disappointment, pessimism', reversed: 'Personal setbacks, self-forgiveness, moving on' },
    meaningUa: { upright: 'Жаль, розчарування, втрата', reversed: 'Самопрощення, рух уперед' },
  },
  {
    id: 'cups-6', numericId: 42, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Six of Cups', nameUa: 'Шістка Кубків',
    keywords: ['revisiting the past', 'childhood memories', 'innocence', 'joy'],
    keywordsUa: ['минуле', 'спогади дитинства', 'невинність', 'радість'],
    image: '/cards/cups-6.jpg',
    meaning: { upright: 'Revisiting the past, childhood memories, innocence, joy', reversed: 'Living in the past, forgiveness, lacking playfulness' },
    meaningUa: { upright: 'Ностальгія, дитячі спогади, невинність', reversed: 'Зациклення на минулому, прощення' },
  },
  {
    id: 'cups-7', numericId: 43, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Seven of Cups', nameUa: 'Сімка Кубків',
    keywords: ['opportunities', 'choices', 'wishful thinking', 'illusion'],
    keywordsUa: ['можливості', 'вибір', 'мрійливість', 'ілюзія'],
    image: '/cards/cups-7.jpg',
    meaning: { upright: 'Opportunities, choices, wishful thinking, illusion', reversed: 'Alignment, personal values, overwhelmed by choices' },
    meaningUa: { upright: 'Можливості, вибір, мрійливість, фантазії', reversed: 'Орієнтири, надмір вибору' },
  },
  {
    id: 'cups-8', numericId: 44, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Eight of Cups', nameUa: 'Вісімка Кубків',
    keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism'],
    keywordsUa: ['розчарування', 'покидання', 'відхід', 'втеча'],
    image: '/cards/cups-8.jpg',
    meaning: { upright: 'Disappointment, abandonment, withdrawal, escapism', reversed: 'Trying one more time, indecision, aimless drifting' },
    meaningUa: { upright: 'Розчарування, відхід, пошук нового шляху', reversed: 'Нерішучість, ще одна спроба' },
  },
  {
    id: 'cups-9', numericId: 45, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Nine of Cups', nameUa: "Дев'ятка Кубків",
    keywords: ['contentment', 'satisfaction', 'gratitude', 'wish come true'],
    keywordsUa: ['задоволеність', 'вдячність', 'здійснення бажань'],
    image: '/cards/cups-9.jpg',
    meaning: { upright: 'Contentment, satisfaction, gratitude, wish come true', reversed: 'Inner happiness, materialism, dissatisfaction' },
    meaningUa: { upright: 'Задоволення, вдячність, здійснення бажань', reversed: 'Внутрішнє щастя, матеріалізм' },
  },
  {
    id: 'cups-10', numericId: 46, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Ten of Cups', nameUa: 'Десятка Кубків',
    keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment'],
    keywordsUa: ['божественне кохання', 'гармонія', 'щастя', 'сім\'я'],
    image: '/cards/cups-10.jpg',
    meaning: { upright: 'Divine love, blissful relationships, harmony, alignment', reversed: 'Disconnection, misaligned values, struggling relationships' },
    meaningUa: { upright: 'Щасливе сімейне життя, гармонія, любов', reversed: 'Розрив, конфлікти' },
  },
  {
    id: 'cups-11', numericId: 47, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Page of Cups', nameUa: 'Паж Кубків',
    keywords: ['creative opportunities', 'intuitive messages', 'curiosity'],
    keywordsUa: ['творчі можливості', 'інтуїтивні послання', 'допитливість'],
    image: '/cards/cups-11.jpg',
    meaning: { upright: 'Creative opportunities, intuitive messages, curiosity, possibility', reversed: 'Emotional immaturity, creative blocks' },
    meaningUa: { upright: 'Творчість, інтуїція, допитливість', reversed: 'Емоційна незрілість, творчий блок' },
  },
  {
    id: 'cups-12', numericId: 48, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Knight of Cups', nameUa: 'Лицар Кубків',
    keywords: ['creativity', 'romance', 'charm', 'imagination'],
    keywordsUa: ['творчість', 'романтика', 'чарівність', 'уява'],
    image: '/cards/cups-12.jpg',
    meaning: { upright: 'Creativity, romance, charm, imagination, beauty', reversed: 'Overactive imagination, jealousy, moodiness' },
    meaningUa: { upright: 'Романтика, творчість, чарівність, ідеалізм', reversed: 'Ревнощі, мінливість настрою' },
  },
  {
    id: 'cups-13', numericId: 49, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'Queen of Cups', nameUa: 'Королева Кубків',
    keywords: ['compassionate', 'caring', 'emotionally stable', 'intuitive'],
    keywordsUa: ['співчутлива', 'дбайлива', 'емоційно стабільна', 'інтуїтивна'],
    image: '/cards/cups-13.jpg',
    meaning: { upright: 'Compassionate, caring, emotionally stable, intuitive, in flow', reversed: 'Martyrdom, insecurity, dependence' },
    meaningUa: { upright: 'Співчуття, турбота, емоційна зрілість', reversed: 'Мучеництво, невпевненість' },
  },
  {
    id: 'cups-14', numericId: 50, arcana: 'minor', suit: 'cups', suitUa: 'Кубків',
    name: 'King of Cups', nameUa: 'Король Кубків',
    keywords: ['emotionally balanced', 'compassionate', 'diplomatic'],
    keywordsUa: ['емоційна рівновага', 'дипломатія', 'мудрість'],
    image: '/cards/cups-14.jpg',
    meaning: { upright: 'Emotionally balanced, compassionate, diplomatic', reversed: 'Self-compassion, inner feelings, moodiness, emotionally manipulative' },
    meaningUa: { upright: 'Емоційна рівновага, дипломатія, мудрість', reversed: 'Мінливість, маніпуляції' },
  },

  // ─── MINOR ARCANA — SWORDS (Мечі) ────────────────────────────────────────────
  {
    id: 'swords-1', numericId: 51, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Ace of Swords', nameUa: 'Туз Мечів',
    keywords: ['breakthrough', 'clarity', 'sharp mind', 'truth'],
    keywordsUa: ['прорив', 'ясність', 'гострий розум', 'правда'],
    image: '/cards/swords-1.jpg',
    meaning: { upright: 'Breakthrough, clarity, sharp mind, truth', reversed: 'Confusion, brutality, chaos' },
    meaningUa: { upright: 'Прорив, ясність думки, правда, нові ідеї', reversed: 'Плутанина, жорстокість, хаос' },
  },
  {
    id: 'swords-2', numericId: 52, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Two of Swords', nameUa: 'Двійка Мечів',
    keywords: ['difficult decisions', 'indecision', 'choices', 'stalemate'],
    keywordsUa: ['важкі рішення', 'нерішучість', 'вибір', 'патова ситуація'],
    image: '/cards/swords-2.jpg',
    meaning: { upright: 'Difficult decisions, indecision, choices, stalemate', reversed: 'Indecision, confusion, information overload' },
    meaningUa: { upright: 'Важкий вибір, нерішучість, патова ситуація', reversed: 'Плутанина, надмір інформації' },
  },
  {
    id: 'swords-3', numericId: 53, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Three of Swords', nameUa: 'Трійка Мечів',
    keywords: ['heartbreak', 'emotional pain', 'sorrow', 'grief'],
    keywordsUa: ['серцевий біль', 'страждання', 'горе', 'туга'],
    image: '/cards/swords-3.jpg',
    meaning: { upright: 'Heartbreak, emotional pain, sorrow, grief, hurt', reversed: 'Negative self-talk, releasing pain, optimism' },
    meaningUa: { upright: 'Серцевий біль, страждання, горе', reversed: 'Відпускання болю, оптимізм' },
  },
  {
    id: 'swords-4', numericId: 54, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Four of Swords', nameUa: 'Четвірка Мечів',
    keywords: ['rest', 'relaxation', 'meditation', 'contemplation'],
    keywordsUa: ['відпочинок', 'розслаблення', 'медитація', 'споглядання'],
    image: '/cards/swords-4.jpg',
    meaning: { upright: 'Rest, relaxation, meditation, contemplation, recuperation', reversed: 'Exhaustion, burnout, restlessness' },
    meaningUa: { upright: 'Відпочинок, відновлення, медитація', reversed: 'Виснаження, безсоння' },
  },
  {
    id: 'swords-5', numericId: 55, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Five of Swords', nameUa: "П'ятірка Мечів",
    keywords: ['conflict', 'disagreements', 'competition', 'defeat'],
    keywordsUa: ['конфлікт', 'суперечки', 'конкуренція', 'поразка'],
    image: '/cards/swords-5.jpg',
    meaning: { upright: 'Conflict, disagreements, competition, defeat, winning at all costs', reversed: 'Reconciliation, making amends, past resentment' },
    meaningUa: { upright: 'Конфлікт, поразка, перемога будь-якою ціною', reversed: 'Примирення, прощення' },
  },
  {
    id: 'swords-6', numericId: 56, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Six of Swords', nameUa: 'Шістка Мечів',
    keywords: ['transition', 'change', 'rite of passage', 'moving on'],
    keywordsUa: ['перехід', 'зміни', 'рух вперед', 'нові береги'],
    image: '/cards/swords-6.jpg',
    meaning: { upright: 'Transition, change, rite of passage, moving on', reversed: 'Personal transition, resistance to change' },
    meaningUa: { upright: 'Перехід, зміни, рух до кращого', reversed: 'Опір змінам, затримка' },
  },
  {
    id: 'swords-7', numericId: 57, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Seven of Swords', nameUa: 'Сімка Мечів',
    keywords: ['betrayal', 'deception', 'getting away with something', 'strategy'],
    keywordsUa: ['зрада', 'обман', 'стратегія', 'хитрість'],
    image: '/cards/swords-7.jpg',
    meaning: { upright: 'Betrayal, deception, getting away with something, strategy', reversed: 'Imposter syndrome, self-deceit, keeping secrets' },
    meaningUa: { upright: 'Зрада, обман, стратегія виживання', reversed: 'Самообман, синдром самозванця' },
  },
  {
    id: 'swords-8', numericId: 58, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Eight of Swords', nameUa: 'Вісімка Мечів',
    keywords: ['imprisonment', 'entrapment', 'self-victimization', 'negative thoughts'],
    keywordsUa: ['ув\'язнення', 'пастка', 'жертовність', 'негативні думки'],
    image: '/cards/swords-8.jpg',
    meaning: { upright: 'Imprisonment, entrapment, self-victimization, negative thoughts', reversed: 'Self-limiting beliefs, inner critic, releasing negative thoughts' },
    meaningUa: { upright: 'Пастка думок, жертовність, обмеження', reversed: 'Звільнення від обмежень' },
  },
  {
    id: 'swords-9', numericId: 59, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Nine of Swords', nameUa: "Дев'ятка Мечів",
    keywords: ['anxiety', 'worry', 'fear', 'depression'],
    keywordsUa: ['тривога', 'страхи', 'депресія', 'безсоння'],
    image: '/cards/swords-9.jpg',
    meaning: { upright: 'Anxiety, worry, fear, depression, nightmares', reversed: 'Inner turmoil, deep-seated fears, secrets' },
    meaningUa: { upright: 'Тривога, страхи, кошмари, нічні думки', reversed: 'Внутрішній хаос, глибокі страхи' },
  },
  {
    id: 'swords-10', numericId: 60, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Ten of Swords', nameUa: 'Десятка Мечів',
    keywords: ['painful endings', 'deep wounds', 'betrayal', 'crisis'],
    keywordsUa: ['болісний кінець', 'глибокі рани', 'зрада', 'криза'],
    image: '/cards/swords-10.jpg',
    meaning: { upright: 'Painful endings, deep wounds, betrayal, crisis, loss', reversed: 'Recovery, regeneration, resisting an inevitable end' },
    meaningUa: { upright: 'Болісний кінець, криза, зрада', reversed: 'Відновлення, опір кінцю' },
  },
  {
    id: 'swords-11', numericId: 61, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Page of Swords', nameUa: 'Паж Мечів',
    keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'vigilance'],
    keywordsUa: ['нові ідеї', 'допитливість', 'спостережливість', 'пильність'],
    image: '/cards/swords-11.jpg',
    meaning: { upright: 'New ideas, curiosity, thirst for knowledge, vigilance', reversed: 'Known unknowns, manipulation, all talk and no action' },
    meaningUa: { upright: 'Нові ідеї, допитливість, пильність', reversed: 'Маніпуляції, слова без дій' },
  },
  {
    id: 'swords-12', numericId: 62, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Knight of Swords', nameUa: 'Лицар Мечів',
    keywords: ['ambitious', 'action-oriented', 'driven', 'fast-thinking'],
    keywordsUa: ['амбіційний', 'цілеспрямований', 'швидкодумаючий'],
    image: '/cards/swords-12.jpg',
    meaning: { upright: 'Ambitious, action-oriented, driven to succeed, fast-thinking', reversed: 'Restless, unfocused, impulsive, hasty' },
    meaningUa: { upright: 'Амбіції, цілеспрямованість, швидкість думки', reversed: 'Нервозність, імпульсивність' },
  },
  {
    id: 'swords-13', numericId: 63, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'Queen of Swords', nameUa: 'Королева Мечів',
    keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct communication'],
    keywordsUa: ['незалежна', 'неупереджена', 'чіткі межі', 'пряме спілкування'],
    image: '/cards/swords-13.jpg',
    meaning: { upright: 'Independent, unbiased judgement, clear boundaries, direct communication', reversed: 'Overly-emotional, easily influenced, bitchy, cold-hearted' },
    meaningUa: { upright: 'Незалежність, чіткість суджень, прямота', reversed: 'Холодність, маніпуляції' },
  },
  {
    id: 'swords-14', numericId: 64, arcana: 'minor', suit: 'swords', suitUa: 'Мечів',
    name: 'King of Swords', nameUa: 'Король Мечів',
    keywords: ['mental clarity', 'intellectual power', 'authority', 'truth'],
    keywordsUa: ['розумова ясність', 'інтелектуальна сила', 'авторитет', 'правда'],
    image: '/cards/swords-14.jpg',
    meaning: { upright: 'Mental clarity, intellectual power, authority, truth', reversed: 'Quiet power, inner truth, misuse of power' },
    meaningUa: { upright: 'Розумова ясність, інтелект, авторитет', reversed: 'Зловживання владою, тиранія' },
  },

  // ─── MINOR ARCANA — PENTACLES (Пентаклі) ─────────────────────────────────────
  {
    id: 'pents-1', numericId: 65, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Ace of Pentacles', nameUa: 'Туз Пентаклів',
    keywords: ['new financial opportunity', 'manifestation', 'abundance', 'security'],
    keywordsUa: ['нові фінансові можливості', 'маніфестація', 'достаток', 'безпека'],
    image: '/cards/pents-1.jpg',
    meaning: { upright: 'New financial opportunity, manifestation, abundance', reversed: 'Lost opportunity, lack of planning and foresight' },
    meaningUa: { upright: 'Нові фінансові можливості, достаток, реалізація', reversed: 'Втрачена можливість, відсутність планування' },
  },
  {
    id: 'pents-2', numericId: 66, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Two of Pentacles', nameUa: 'Двійка Пентаклів',
    keywords: ['multiple priorities', 'time management', 'prioritization', 'adaptability'],
    keywordsUa: ['баланс', 'управління часом', 'пріоритети', 'адаптивність'],
    image: '/cards/pents-2.jpg',
    meaning: { upright: 'Multiple priorities, time management, prioritization, adaptability', reversed: 'Over-committed, disorganisation, reprioritisation' },
    meaningUa: { upright: 'Баланс, управління часом, адаптивність', reversed: 'Надмірні зобов\'язання, дезорганізація' },
  },
  {
    id: 'pents-3', numericId: 67, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Three of Pentacles', nameUa: 'Трійка Пентаклів',
    keywords: ['teamwork', 'collaboration', 'building', 'implementation'],
    keywordsUa: ['командна робота', 'співпраця', 'будівництво', 'реалізація'],
    image: '/cards/pents-3.jpg',
    meaning: { upright: 'Teamwork, collaboration, building, implementation', reversed: 'Lack of teamwork, disorganised, group conflict' },
    meaningUa: { upright: 'Командна робота, співпраця, майстерність', reversed: 'Відсутність командної роботи, конфлікт' },
  },
  {
    id: 'pents-4', numericId: 68, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Four of Pentacles', nameUa: 'Четвірка Пентаклів',
    keywords: ['saving money', 'security', 'conservatism', 'scarcity'],
    keywordsUa: ['заощадження', 'безпека', 'консерватизм', 'скупість'],
    image: '/cards/pents-4.jpg',
    meaning: { upright: 'Saving money, security, conservatism, scarcity, control', reversed: 'Over-spending, greed, self-protection' },
    meaningUa: { upright: 'Заощадження, безпека, стабільність', reversed: 'Скупість, надмірний контроль над фінансами' },
  },
  {
    id: 'pents-5', numericId: 69, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Five of Pentacles', nameUa: "П'ятірка Пентаклів",
    keywords: ['financial loss', 'poverty', 'lack mindset', 'isolation'],
    keywordsUa: ['фінансові втрати', 'бідність', 'ізоляція', 'нестаток'],
    image: '/cards/pents-5.jpg',
    meaning: { upright: 'Financial loss, poverty, lack mindset, isolation, worry', reversed: 'Recovery from financial loss, spiritual poverty' },
    meaningUa: { upright: 'Фінансові труднощі, бідність, ізоляція', reversed: 'Відновлення після втрат' },
  },
  {
    id: 'pents-6', numericId: 70, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Six of Pentacles', nameUa: 'Шістка Пентаклів',
    keywords: ['giving', 'receiving', 'sharing wealth', 'generosity'],
    keywordsUa: ['давати', 'отримувати', 'щедрість', 'благодійність'],
    image: '/cards/pents-6.jpg',
    meaning: { upright: 'Giving, receiving, sharing wealth, generosity, charity', reversed: 'Self-care, unpaid debts, one-sided charity' },
    meaningUa: { upright: 'Щедрість, благодійність, обмін ресурсами', reversed: 'Однобічна благодійність, борги' },
  },
  {
    id: 'pents-7', numericId: 71, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Seven of Pentacles', nameUa: 'Сімка Пентаклів',
    keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment'],
    keywordsUa: ['довгострокова перспектива', 'результати', 'наполегливість', 'інвестиції'],
    image: '/cards/pents-7.jpg',
    meaning: { upright: 'Long-term view, sustainable results, perseverance, investment', reversed: 'Lack of long-term vision, limited success or reward' },
    meaningUa: { upright: 'Довгострокова перспектива, результати праці', reversed: 'Відсутність терпіння, обмежений результат' },
  },
  {
    id: 'pents-8', numericId: 72, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Eight of Pentacles', nameUa: 'Вісімка Пентаклів',
    keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
    keywordsUa: ['учнівство', 'майстерність', 'розвиток навичок', 'ремесло'],
    image: '/cards/pents-8.jpg',
    meaning: { upright: 'Apprenticeship, repetitive tasks, mastery, skill development', reversed: 'Self-development, perfectionism, misdirected activity' },
    meaningUa: { upright: 'Майстерність, розвиток навичок, старанність', reversed: 'Перфекціонізм, неправильний напрям' },
  },
  {
    id: 'pents-9', numericId: 73, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Nine of Pentacles', nameUa: "Дев'ятка Пентаклів",
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
    keywordsUa: ['достаток', 'розкіш', 'самодостатність', 'фінансова незалежність'],
    image: '/cards/pents-9.jpg',
    meaning: { upright: 'Abundance, luxury, self-sufficiency, financial independence', reversed: 'Self-worth, over-investment in work, hustling' },
    meaningUa: { upright: 'Достаток, розкіш, фінансова незалежність', reversed: 'Самоцінність, надмірна робота' },
  },
  {
    id: 'pents-10', numericId: 74, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Ten of Pentacles', nameUa: 'Десятка Пентаклів',
    keywords: ['wealth', 'financial security', 'family', 'long-term success'],
    keywordsUa: ['багатство', 'фінансова безпека', 'сім\'я', 'довгостроковий успіх'],
    image: '/cards/pents-10.jpg',
    meaning: { upright: 'Wealth, financial security, family, long-term success, contribution', reversed: 'The dark side of wealth, financial failure or loss' },
    meaningUa: { upright: 'Багатство, сімейна безпека, спадщина', reversed: 'Темна сторона багатства, фінансові втрати' },
  },
  {
    id: 'pents-11', numericId: 75, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Page of Pentacles', nameUa: 'Паж Пентаклів',
    keywords: ['manifestation', 'financial opportunity', 'skill development'],
    keywordsUa: ['маніфестація', 'фінансові можливості', 'розвиток навичок'],
    image: '/cards/pents-11.jpg',
    meaning: { upright: 'Manifestation, financial opportunity, skill development', reversed: 'Lack of progress, procrastination, learn from failure' },
    meaningUa: { upright: 'Маніфестація, можливості, навчання', reversed: 'Відсутність прогресу, прокрастинація' },
  },
  {
    id: 'pents-12', numericId: 76, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Knight of Pentacles', nameUa: 'Лицар Пентаклів',
    keywords: ['hard work', 'productivity', 'routine', 'conservatism'],
    keywordsUa: ['наполеглива праця', 'прод��ктивність', 'рутина', 'консерватизм'],
    image: '/cards/pents-12.jpg',
    meaning: { upright: 'Hard work, productivity, routine, conservatism', reversed: 'Self-discipline, boredom, feeling stuck, perfectionism' },
    meaningUa: { upright: 'Наполеглива праця, стабільність, відданість', reversed: 'Нудьга, застрягання, перфекціонізм' },
  },
  {
    id: 'pents-13', numericId: 77, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'Queen of Pentacles', nameUa: 'Королева Пентаклів',
    keywords: ['nurturing', 'practical', 'providing financially', 'a working parent'],
    keywordsUa: ['турботлива', 'практична', 'фінансова стабільність', 'практичність'],
    image: '/cards/pents-13.jpg',
    meaning: { upright: 'Nurturing, practical, providing financially, a working parent', reversed: 'Financial independence, self-care, work-home conflict' },
    meaningUa: { upright: 'Турботливість, практичність, фінансова стабільність', reversed: 'Фінансова незалежність, конфлікт роботи і дому' },
  },
  {
    id: 'pents-14', numericId: 78, arcana: 'minor', suit: 'pentacles', suitUa: 'Пентаклів',
    name: 'King of Pentacles', nameUa: 'Король Пентаклів',
    keywords: ['wealth', 'business', 'leadership', 'security'],
    keywordsUa: ['багатство', 'бізнес', 'лідерство', 'безпека'],
    image: '/cards/pents-14.jpg',
    meaning: { upright: 'Wealth, business, leadership, security, discipline, abundance', reversed: 'Financially inept, obsessed with wealth and status, stubborn' },
    meaningUa: { upright: 'Багатство, бізнес-лідерство, стабільність', reversed: 'Фінансова некомпетентність, одержимість статусом' },
  },
]

export function getCardById(id: string): TarotCard | undefined {
  return ALL_CARDS.find(c => c.id === id)
}

// Deck system - creates a shuffled deck that cards are drawn from
export function createShuffledDeck(): TarotCard[] {
  const deck = [...ALL_CARDS]
  // Fisher-Yates shuffle for proper randomization
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[deck[i], deck[j]] = [deck[j], deck[i]]
  }
  return deck
}

export function drawCardsFromDeck(deck: TarotCard[], count: number): { drawnCards: TarotCard[]; remainingDeck: TarotCard[] } {
  const drawnCards = deck.slice(0, count)
  const remainingDeck = deck.slice(count)
  return { drawnCards, remainingDeck }
}

// Legacy function for backwards compatibility
export function getRandomCards(count = 3): TarotCard[] {
  return createShuffledDeck().slice(0, count)
}
